heat_template_version: 2015-10-15
description: Create a server for RestoringValuesSPbPU project

resources:
  # Описываем сервер
  my_server:
    type: OS::Nova::Server
    properties:
      name: Nikita-ML-Server       # Имя будущей машины
      image: ununtu-22.04           # Образ
      flavor: m1.small              # Размер
      key_name: Nikita_Alecsentsev  # Ключ
      networks:
        - network: sutdents-net     # Сеть
      
      # Метаданные для идентификации
      metadata:
        project: "RestoringValuesSPbPU"
        owner: "Nikita Alecsentsev"
      
      # Скрипт для первоначальной настройки (user_data)
      user_data: |
        #!/bin/bash
        echo "Сервер создан через Heat" > /etc/motd
        echo "Проект: RestoringValuesSPbPU" >> /etc/motd
        echo "Дата создания: $(date)" >> /etc/motd
